import type { Metadata } from "next";
import {Manrope} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Header/Footer";
import { CartProvider } from "@/context/CartContext";

// Configure the font
const manrope = Manrope({
  subsets: ["latin"],
  display: "swap", 
  variable: "--font-manrope", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.variable}>
        <CartProvider> {/* --- Add this opening tag --- */}
          <Header />
          {children}
          <Footer />
        </CartProvider> {/* --- Add this closing tag --- */}
      </body>
    </html>
  );
}
